# Generated by Django 5.2.7 on 2026-03-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='registration_open',
            field=models.BooleanField(default=True, verbose_name='Registration open'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('meet', 'email'), name='unique_registration_email_per_meet'),
        ),
    ]
