# Generated by Django 5.2.7 on 2026-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_alter_meet_date_alter_meet_location_alter_meet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='weight_class',
            field=models.CharField(choices=[('-59', '-59 kg'), ('-66', '-66 kg'), ('-74', '-74 kg'), ('-83', '-83 kg'), ('-93', '-93 kg'), ('-105', '-105 kg'), ('-120', '-120 kg'), ('+120', '+120 kg')], max_length=10),
        ),
    ]
