# Generated by Django 5.2.7 on 2026-03-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0003_alter_registration_weight_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='sex',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='Men', max_length=10),
        ),
    ]
