# Generated by Django 5.2.7 on 2026-03-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0004_registration_sex'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_registration_email_per_meet',
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('meet', 'email')},
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meets.meet'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sex',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='weight_class',
            field=models.CharField(choices=[('59', '59 kg'), ('66', '66 kg'), ('74', '74 kg'), ('83', '83 kg'), ('93', '93 kg'), ('105', '105 kg'), ('120', '120 kg'), ('120+', '120+ kg'), ('47', '47 kg'), ('52', '52 kg'), ('57', '57 kg'), ('63', '63 kg'), ('69', '69 kg'), ('76', '76 kg'), ('84', '84 kg'), ('84+', '84+ kg')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='paid',
        ),
    ]
