# Generated by Django 5.2.7 on 2026-04-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0005_remove_registration_unique_registration_email_per_meet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='meets.meet'),
        ),
    ]
