# Generated by Django 5.2.7 on 2026-05-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0006_alter_registration_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='registration',
            name='discipline',
            field=models.CharField(choices=[('raw_powerlifting', 'Raw Powerlifting'), ('classic_powerlifting', 'Classic Powerlifting'), ('squat', 'Squat'), ('bench_press', 'Bench Press'), ('deadlift', 'Deadlift')], default='raw_powerlifting', max_length=30, verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='weight_class',
            field=models.CharField(choices=[('men_52', '52 kg'), ('men_56', '56 kg'), ('men_60', '60 kg'), ('men_67.5', '67.5 kg'), ('men_75', '75 kg'), ('men_82.5', '82.5 kg'), ('men_90', '90 kg'), ('men_100', '100 kg'), ('men_110', '110 kg'), ('men_125', '125 kg'), ('men_140', '140 kg'), ('men_140+', '140+ kg'), ('women_44', '44 kg'), ('women_48', '48 kg'), ('women_52', '52 kg'), ('women_56', '56 kg'), ('women_60', '60 kg'), ('women_67.5', '67.5 kg'), ('women_75', '75 kg'), ('women_82.5', '82.5 kg'), ('women_90', '90 kg'), ('women_90+', '90+ kg')], max_length=10),
        ),
    ]
