# Generated by Django 5.2.7 on 2026-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0007_registration_date_of_birth_registration_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payment confirmed'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_notes',
            field=models.TextField(blank=True, verbose_name='Payment notes'),
        ),
    ]
