# Generated by Django 5.2.7 on 2026-05-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0008_registration_paid_registration_payment_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meet',
            options={'verbose_name': 'Meet', 'verbose_name_plural': 'Meets'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
    ]
