# Generated by Django 5.2.7 on 2026-05-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0009_alter_meet_options_alter_registration_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='discipline',
        ),
        migrations.AddField(
            model_name='registration',
            name='disciplines',
            field=models.JSONField(blank=True, default=list, verbose_name='Disciplines'),
        ),
    ]
