# Generated by Django 5.2.7 on 2026-06-03 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0010_remove_registration_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='divisions',
            field=models.JSONField(blank=True, default=list, verbose_name='Divisions'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_tested',
            field=models.BooleanField(default=False, verbose_name='Anti-doping tested'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='meets.meet', verbose_name='Meet'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sex',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='weight_class',
            field=models.CharField(choices=[('men_52', '52 kg'), ('men_56', '56 kg'), ('men_60', '60 kg'), ('men_67.5', '67.5 kg'), ('men_75', '75 kg'), ('men_82.5', '82.5 kg'), ('men_90', '90 kg'), ('men_100', '100 kg'), ('men_110', '110 kg'), ('men_125', '125 kg'), ('men_140', '140 kg'), ('men_140+', '140+ kg'), ('women_44', '44 kg'), ('women_48', '48 kg'), ('women_52', '52 kg'), ('women_56', '56 kg'), ('women_60', '60 kg'), ('women_67.5', '67.5 kg'), ('women_75', '75 kg'), ('women_82.5', '82.5 kg'), ('women_90', '90 kg'), ('women_90+', '90+ kg')], max_length=10, verbose_name='Weight class'),
        ),
    ]
