# Generated by Django 5.2.7 on 2026-06-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0011_registration_divisions_alter_registration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='payment_information',
            field=models.TextField(blank=True, verbose_name='Payment information'),
        ),
    ]
