# Generated by Django 5.2.7 on 2026-06-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0012_meet_payment_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='disciplines',
            field=models.JSONField(default=list, verbose_name='Disciplines'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='divisions',
            field=models.JSONField(default=list, verbose_name='Divisions'),
        ),
    ]
